# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0145961b9c32c768142a241162f0ba0e6fa05d2e40cda375d7333b94f49fd2ea4b2b0731ce6213721a6f816be40cc1e56f52a733014d31b083b55b31af95bf50

test:
  secret_key_base: eeef257749d560b89497b3466bea979410c8ed908a61eed4eed4a19f51a8617a0740d316f0868306583afba827f41cad5abfc33bfcd22720baf2635eebfe7156

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
